CREATE DATABASE IF NOT EXISTS ssr_blog DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
USE ssr_blog;

CREATE TABLE IF NOT EXISTS articles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  summary VARCHAR(1024) DEFAULT NULL,
  content LONGTEXT NOT NULL,
  author VARCHAR(80) DEFAULT 'admin',
  status ENUM('published','draft') DEFAULT 'published',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT(1) DEFAULT 0,
  views INT UNSIGNED DEFAULT 0,
  tags VARCHAR(255) DEFAULT NULL,
  FULLTEXT KEY ft_title_summary (title, summary)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
